name: wallpaperapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: any
  get: any
  open_file: ^3.2.1
  image_downloader: ^0.31.0
  permission_handler: ^11.3.1
  gallery_saver: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  fluttertoast: ^8.2.8

flutter:
  uses-material-design: true
